// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udfdezexhlkwrghhgxem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZmRlemV4aGxrd3JnaGhneGVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyOTg2NDMsImV4cCI6MjA5MDg3NDY0M30.V952dV73BaRAfc3R8Er_6cBanlUF1xaLGrTKN7vEwDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});